@startuml

hide circle

class Client <<Entity>>

class Jaar <<Entity>>

rectangle "Aggregate\n" {
    class Dag <<AR>> {
        maakAfspraak(tijdslot, client)
    }

    class Slot <<Value Object>> {
        slotnummer
    }

    class Afspraak <<Value Object>>
}

Afspraak "1" -r-> "  1..2" Slot
Dag "1" --> "40" Slot
Dag "\t\t\t1" --> "0..40" Afspraak

Jaar "1" ---> "240" Dag
Afspraak "1" --> "1" Client


@enduml