@startuml

autonumber

actor Leverancier

participant productController as "productController:\nbestellingController"
participant product as "product:\nProduct"
participant bestellingMetProduct as "bestellingMetProduct:\nBestelling"

database productRepository as "productRepository:\nProductRepository"
database bestellingRepository as "bestellingRepository:\nBestellingRepository"

participant bestelling as "bestelling:\nBestelling"
participant bestellingController as "bestellingController:\nbestellingController"


actor Instellingsmedewerker as Instelling

Leverancier --> productController: veranderPrijs\n\
    (productId, nieuwePrijs)

Instelling --> bestellingController: plaatsBestelling\n\
    (bestellingId)


@enduml