### GET Bestellingen 1

GET http://localhost:8080/bestellingen/1

### GET Bestellingen 2

GET http://localhost:8080/bestellingen/2

### GET Product 1 (tafel)

GET http://localhost:8080/producten/1

### GET Product 2 (stoel)

GET http://localhost:8080/producten/2

### GET Product 3 (bank)

GET http://localhost:8080/producten/3


### Voeg product 2 (stoel) toe aan bestelling 2

POST http://localhost:8080/bestellingen/2/producten
Content-Type: application/json

{
  "product_id": 2,
  "aantal": 2
}

### Voeg product 2 (stoel) voor de tweede keer toe aan bestelling 1 (verwacht internal server error)

POST http://localhost:8080/bestellingen/1/producten
Content-Type: application/json

{
  "product_id": 2,
  "aantal": 1
}

### Plaatst bestelling 1

PATCH http://localhost:8080/bestellingen/1/plaats
Content-Type: application/json
