@startuml

autonumber

actor "Bezoeker1" as bezoeker1
participant "dagplanningController:\nDagplanningController" as controller1
participant "dagplanning:\nDagplanning" as dagplanning1
participant "vertoning\nVertoning" as vertoning1
database "dagplanning\nRepository" as dagplanningRepo
participant "vertoning\nVertoning" as vertoning2
participant "dagplanning:\nDagplanning" as dagplanning2
participant "dagplanningController:\nDagplanningController" as controller2
actor "Bezoeker2" as bezoeker2

bezoeker1 -> controller1 : PATCH dagplanning/5\n\
{\n\
    datum: 01-01-2025,\n\
    starttijd: 12:00,\n\
    eindtijd: 14:00,\n\
    filmId: 255\n\
}

controller1 -> dagplanningRepo: dagplanning = findDagplanning(dagplanningId)

controller1 -> vertoning1 **: vertoning = new Vertoning(datum, starttijd, eindtijd, filmId)

controller1 -> dagplanning1: voegToe(vertoning)

dagplanning1 -> dagplanning1: geenConflict = veroorzaaktGeenConflict(vertoning)

alt geenConflict
    dagplanning1 -> dagplanning1: add(vertoning)
    controller1 -> dagplanningRepo: save(dagplanning)
end

@enduml