@startuml

hide circle

rectangle "DagAgenda Aggregate" {
    class DagAgenda <<AR>> {
        id: Integer
        datum: LocalDate
        voegToe(Vertoning vertoning)
    }

    class Vertoning <<Value Object>> {
        locatie: String
        starttijd: LocalTime
        eindtijd: LocalTime
        overlaptMet(Vertoning vertoning): boolean
    }
}

rectangle "Aggregate Film\n" {
    class Film <<AR>> {
        id: Integer
        titel: String
        duur: Integer
}

DagAgenda "1" --> " vertoningen *" Vertoning

Vertoning "1" --> "film 1" Film

@enduml