@startuml

hide circle

'left to right direction

'skinparam linetype ortho
'skinparam linetype polyline

rectangle "Bezoeker Aggregate" {
    class Bezoeker <<AR>> {
        id: Integer
        naam: String
    }
}

rectangle "Film Aggregate" {
    class Film <<AR>> {
        id: Integer
        naam: String
    }
}

rectangle "Dagplanning Aggregate" {
    class Dagplanning <<AR>> {
        id: Integer
        datum: LocalDate
        voegToe(Vertoning vertoning)
    }

    class Vertoning <<Value Object>> {
        startTijd: LocalTime
        eindTijd: LocalTime
        locatie: String
    }
}

Bezoeker "*" --- "dagplanningen *\n\n" Dagplanning

Dagplanning "1" --> " vertoningen *" Vertoning

Vertoning "1   " --> "film 1" Film

@enduml