@startuml

autonumber

title "Bezoeker 1 en 2 proberen beiden een vertoning toe te voegen aan dezelfde dagagenda"

actor "Bezoeker1" as bezoeker1
participant "dagplanningController:\nDagplanningController" as controller1

participant "dagplanningController:\nDagplanningController" as controller2
actor "Bezoeker2" as bezoeker2

bezoeker1 -> controller1 : POST dagagendas/1/vertoningen/1
note left
Bezoeker1 probeert
vertoning 1 toe te voegen
aan dagplanning 1
end note

bezoeker2 -> controller2 : POST dagagendas/1/vertoningen/2
note right
Bezoeker2 probeert
vertoning 2 toe te voegen
aan dagplanning 1
end note

@enduml