@startuml

actor bezoeker1

participant "vertoningController\n:VertoningController" as vc1
participant "vertoning\n:Vertoning" as v1
database VertoningRepository
participant "vertoning\n:Vertoning" as v2
participant "vertoningController\n:VertoningController" as vc2

actor bezoeker2

bezoeker1 -> vc1: PATCH /vertoning/1/reserveer \n\
        { \n\
            "zitplaatsId": 1 \n\
        }

bezoeker2 -> vc2: PATCH /vertoning/1/reserveer \n\
        { \n\
            "zitplaatsId": 2 \n\
        }


@enduml