@startuml

autonumber

actor bezoeker1

participant "vertoningController\n:VertoningController" as vc1
participant "zitplaats1\n:Zitplaats" as z1
database ZitplaatsRepository
participant "zitplaats2\n:Zitplaats" as z2
participant "vertoningController\n:VertoningController" as vc2

actor bezoeker2

bezoeker1 -> vc1: PATCH /zitplaats/1/reserveer

bezoeker2 -> vc2: PATCH /zitplaats/2/reserveer




@enduml