@startuml

hide circle

left to right direction

rectangle "Aggregate Vertoning" {
    class Vertoning <<AR>> {
        id
        datum
        tijd
        film
        zaal
    }
}
rectangle "Aggregate Zitplaats" {
    class Zitplaats <<AR>> {
        id
        isBeschikbaar
        reserveer()
    }
}

Vertoning "vertoning 1" --- "*" Zitplaats
@enduml
