@startuml

hide circle


rectangle "Post Aggregate" {

    class Post <<Aggregate Root>> {
        addComment(comment)
        addComments(comments)
    }

    class Comment <<Value Object>> {
    }
}

rectangle "Author Aggregate" {

    class Author <<Aggregate Root>> {
    }

}
Post "post 1" -- "comments *" Comment
Post "*" -r-> "author \n 1" Author: \t\t

@enduml
