@startuml

autonumber

actor "Bezoeker1" as bezoeker1
participant "dagAgendaController:\ndagAgendaController" as controller1
participant "dagAgenda:\ndagAgenda" as dagAgenda1
participant "vertoning\nVertoning" as vertoning1
database "dagAgenda\nRepository" as dagAgendaRepo
participant "vertoning\nVertoning" as vertoning2
participant "dagAgenda:\ndagAgenda" as dagAgenda2
participant "dagAgendaController:\ndagAgendaController" as controller2
actor "Bezoeker2" as bezoeker2

bezoeker1 -> controller1 : POST dagagendas/1/vertoningen\n\

bezoeker2 -> controller2 : POST dagagendas/1/vertoningen\n\

@enduml